### ISSUE TITLE
checkpoints missing

### ISSUE THREAD

**Issue by gleblebedev** [SK4P3/blip-image-captioning-docker#1]
When running the powershell file
docker build -t py-worker .
it fails on
#7 [2/7] ADD ./checkpoints /app/checkpoints
#7 sha256:66385eb2b9e14ebca5144f4dc9ed2f54ac7cfa4adfaee182aaf2035af0103d3b
#7 ERROR: "/checkpoints" not found: not found

the readme says:
- After running it locally for the first time, there should be a /checkpoints folder with the BLIP model
    - So the docker container can copy it and doesnt need to download it again

It seems that there is step missing somewhere.

Shall I just drop model_base_caption_capfilt_large.pth  in the folder?

**Comment by SK4P3** [comment]
yes manually adding the .pth file in the /checkpoints folder should work. Did you run it locally first? It should download everything however it could be broken as its been a while since i made/updated it ;)

**Comment by gleblebedev** [comment]
> It should download everything however it could be broken as its been a while since i made/updated it ;)

It doesn't download the model file, I had to copy it manually from SD. Also i've noticed that documentation says "imgurl" when it actually expects "imgurls" field. Otherwise seems to work fine...

Would be nice not to reload model on each request too:

D00>])
Loading Model...
load checkpoint from ./checkpoints/model_large_caption.pth
Model to cuda:0
Captioning started
['a video game scene of two knights fighting in a field

**Comment by gleblebedev** [comment]
In general it still saved me some time. I'm not familiar with python and this docker image helped me to make a prototype app.

Here is how I run it:

docker run -it --rm -p 5000:5000 --gpus=all py-worker

May worth to add this to readme too.

**Comment by SK4P3** [comment]
nice! glad it works now.
